// GENERATED by tool/mapgen/nk_gen.mjs — 손으로 수정하지 말 것.
// 북한(업데이트 예정) 장식 레이어 좌표. 남한 지도(convert.mjs)와 동일한 투영으로
// 실제 경위도(압록강·두만강 국경, 동·서해안)를 근사 베이크했고, 남쪽 변은
// korea_sigungu.json 에서 추출한 남한 실제 북쪽 경계(+12px 파묻기)라
// 남한 위에 빈틈없이 붙는다(북한은 남한보다 먼저=뒤에 그린다).
import 'dart:ui';

/// 남한 path 를 아래로 내려 위쪽에 북한 밴드를 확보하는 높이(viewBox 단위).
const double kNorthKoreaBand = 524;

/// 북한 외곽 실루엣(최종 viewBox 좌표, 닫힌 폴리곤).
const List<Offset> kNkOutline = [
  Offset(190.4, 635.1),
  Offset(166.7, 643.3),
  Offset(143, 635.1),
  Offset(119.3, 644.5),
  Offset(95.6, 635.1),
  Offset(62.5, 650.3),
  Offset(41.6, 637.5),
  Offset(19.8, 600),
  Offset(41.6, 576.7),
  Offset(62.5, 570.8),
  Offset(86.1, 541.6),
  Offset(88, 527.6),
  Offset(70, 506.5),
  Offset(81.4, 471.4),
  Offset(89, 442.2),
  Offset(109.8, 430.5),
  Offset(76.7, 422.3),
  Offset(48.2, 413),
  Offset(17.9, 401.3),
  Offset(-5.8, 375.6),
  Offset(29.3, 345.2),
  Offset(57.7, 325.3),
  Offset(90.9, 305.4),
  Offset(114.6, 284.4),
  Offset(143, 278.6),
  Offset(166.7, 255.2),
  Offset(199.8, 220.1),
  Offset(228.3, 179.2),
  Offset(261.4, 202.6),
  Offset(299.3, 208.4),
  Offset(332.5, 210.7),
  Offset(346.7, 179.2),
  Offset(341.9, 144.1),
  Offset(379.8, 141.8),
  Offset(427.2, 144.1),
  Offset(465.1, 114.9),
  Offset(503, 91.5),
  Offset(522, 56.4),
  Offset(559.9, 33),
  Offset(588.3, 95),
  Offset(591.1, 109),
  Offset(559.9, 120.7),
  Offset(522, 155.8),
  Offset(498.3, 196.7),
  Offset(474.6, 237.6),
  Offset(446.2, 278.6),
  Offset(408.3, 313.6),
  Offset(351.4, 377.9),
  Offset(323, 395.5),
  Offset(294.6, 413),
  Offset(282.3, 448.1),
  Offset(280.4, 473.8),
  Offset(308.8, 494.8),
  Offset(337.2, 512.4),
  Offset(360.9, 529.9),
  Offset(372.3, 539.3),
  Offset(372, 552),
  Offset(360, 575),
  Offset(348, 584),
  Offset(336, 589),
  Offset(324, 587),
  Offset(312, 584),
  Offset(300, 584),
  Offset(288, 585),
  Offset(276, 585),
  Offset(264, 585),
  Offset(252, 589),
  Offset(240, 597),
  Offset(228, 611),
  Offset(216, 627),
  Offset(204, 651),
  Offset(192, 645),
];

/// 도 경계 + 시·군 보조 분할선(실루엣에 클립해 그린다).
const List<List<Offset>> kNkDividers = [
  [
    Offset(143, 611.7),
    Offset(161.9, 570.8),
    Offset(157.2, 541.6),
  ],
  [
    Offset(88, 529.9),
    Offset(143, 520.5),
    Offset(199.8, 527.6),
    Offset(237.7, 541.6),
  ],
  [
    Offset(237.7, 541.6),
    Offset(251.9, 500.7),
    Offset(233, 465.6),
  ],
  [
    Offset(233, 465.6),
    Offset(282.3, 450.4),
  ],
  [
    Offset(109.8, 430.5),
    Offset(152.5, 436.4),
    Offset(195.1, 413),
    Offset(223.5, 383.8),
  ],
  [
    Offset(223.5, 383.8),
    Offset(237.7, 430.5),
    Offset(233, 465.6),
  ],
  [
    Offset(90.9, 305.4),
    Offset(133.5, 342.8),
    Offset(180.9, 360.4),
    Offset(223.5, 383.8),
  ],
  [
    Offset(223.5, 383.8),
    Offset(261.4, 342.8),
    Offset(294.6, 313.6),
  ],
  [
    Offset(294.6, 313.6),
    Offset(299.3, 261),
    Offset(299.3, 208.4),
  ],
  [
    Offset(294.6, 313.6),
    Offset(346.7, 307.8),
    Offset(394.1, 290.2),
    Offset(431.9, 261),
  ],
  [
    Offset(427.2, 144.1),
    Offset(431.9, 202.6),
    Offset(431.9, 261),
  ],
  [
    Offset(431.9, 261),
    Offset(446.2, 278.6),
  ],
  [
    Offset(34, 383.8),
    Offset(76.7, 389.6),
    Offset(109.8, 377.9),
  ],
  [
    Offset(43.5, 582.5),
    Offset(90.9, 588.4),
    Offset(124, 605.9),
  ],
  [
    Offset(176.1, 313.6),
    Offset(218.8, 331.2),
    Offset(261.4, 342.8),
  ],
  [
    Offset(323, 249.3),
    Offset(365.6, 255.2),
    Offset(394.1, 290.2),
  ],
  [
    Offset(469.8, 150),
    Offset(474.6, 196.7),
  ],
  [
    Offset(157.2, 477.3),
    Offset(199.8, 489),
  ],
  [
    Offset(90.9, 489),
    Offset(128.8, 480.8),
    Offset(152.5, 500.7),
  ],
  [
    Offset(109.8, 377.9),
    Offset(133.5, 342.8),
  ],
  [
    Offset(465.1, 114.9),
    Offset(484.1, 161.6),
    Offset(498.3, 196.7),
  ],
  [
    Offset(522, 97.3),
    Offset(507.7, 138.3),
  ],
  [
    Offset(346.7, 179.2),
    Offset(370.4, 225.9),
    Offset(394.1, 290.2),
  ],
  [
    Offset(294.6, 313.6),
    Offset(327.7, 354.5),
    Offset(351.4, 377.9),
  ],
  [
    Offset(242.5, 377.9),
    Offset(280.4, 401.3),
    Offset(294.6, 413),
  ],
  [
    Offset(57.7, 325.3),
    Offset(90.9, 366.2),
    Offset(109.8, 377.9),
  ],
  [
    Offset(166.7, 255.2),
    Offset(204.6, 296.1),
    Offset(218.8, 331.2),
  ],
  [
    Offset(251.9, 500.7),
    Offset(289.8, 512.4),
    Offset(323, 520.5),
  ],
  [
    Offset(195.1, 529.9),
    Offset(199.8, 570.8),
  ],
  [
    Offset(89, 442.2),
    Offset(138.2, 459.8),
    Offset(176.1, 465.6),
  ],
];

/// "업데이트 예정" 배지 중심.
const Offset kNkLabelCenter = Offset(242.5, 325.3);
