// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR7fMiG85u4ylnfU6LdQCoMNyAG3kVW34',
    appId: '1:625310637326:web:528db730bdedae31eb8b5f',
    messagingSenderId: '625310637326',
    projectId: 'digda-792fa',
    authDomain: 'digda-792fa.firebaseapp.com',
    storageBucket: 'digda-792fa.firebasestorage.app',
    measurementId: 'G-VVVDYSVK7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAWjEucxLMQqHPea8kLUGU6NunZcbln_g',
    appId: '1:625310637326:android:fd144132814cef7deb8b5f',
    messagingSenderId: '625310637326',
    projectId: 'digda-792fa',
    storageBucket: 'digda-792fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIoq6QMfQza5MovIQ7D4GlRr4yMkrlyEc',
    appId: '1:625310637326:ios:4fe7a76eb42818eeeb8b5f',
    messagingSenderId: '625310637326',
    projectId: 'digda-792fa',
    storageBucket: 'digda-792fa.firebasestorage.app',
    iosBundleId: 'com.digda.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIoq6QMfQza5MovIQ7D4GlRr4yMkrlyEc',
    appId: '1:625310637326:ios:4fe7a76eb42818eeeb8b5f',
    messagingSenderId: '625310637326',
    projectId: 'digda-792fa',
    storageBucket: 'digda-792fa.firebasestorage.app',
    iosBundleId: 'com.digda.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR7fMiG85u4ylnfU6LdQCoMNyAG3kVW34',
    appId: '1:625310637326:web:1927f1f8c91b79deeb8b5f',
    messagingSenderId: '625310637326',
    projectId: 'digda-792fa',
    authDomain: 'digda-792fa.firebaseapp.com',
    storageBucket: 'digda-792fa.firebasestorage.app',
    measurementId: 'G-LG2BWFB0EC',
  );
}
